plugins {
	id 'java'
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.boot.dependency.management)
	id 'com.google.protobuf' version '0.9.5'
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'aggregation-grpc-server'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// Flyway
	implementation libs.flyway.core
	implementation libs.flyway.postgresql
	implementation libs.flyway.plugin
	// Postgresql
	implementation("org.postgresql:postgresql")
	runtimeOnly 'org.postgresql:postgresql'
	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	// gRPC
	implementation libs.spring.grpc.starter
	implementation libs.spring.grpc.core
}

//tasks.named('test') {
//	useJUnitPlatform()
//}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:3.25.8"
	}
	plugins {
		grpc {
			artifact = 'io.grpc:protoc-gen-grpc-java:1.76.0'
		}
	}
	generateProtoTasks {
		all()*.plugins {
			grpc {}
		}
	}
}
