plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.boot.dependency.management)
    alias(libs.plugins.protobuf)
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'aggregation-grpc-client'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Aspect
    implementation libs.aspectj.tools
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // Mapstruct
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    // gRPC
    implementation libs.spring.grpc.starter
    implementation libs.spring.grpc.core
}

//tasks.named('test') {
//    useJUnitPlatform()
//}

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:3.25.8"
    }
    plugins {
        grpc {
            artifact = 'io.grpc:protoc-gen-grpc-java:1.76.0'
        }
    }
    generateProtoTasks {
        all()*.plugins {
            grpc {}
        }
    }
}
