plugins {
    id 'java'
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.boot.dependency.management)
}

group = 'com'
version = '0.0.1-SNAPSHOT'
description = 'aggregation-jpa'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Swagger
    implementation libs.springdoc
    // Spring
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    // Hibernate
    implementation 'org.hibernate:hibernate-core:6.6.6.Final'
    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    // Mapstruct
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    // Database
    implementation("org.postgresql:postgresql")
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    // Migration
    implementation 'org.liquibase:liquibase-core:4.25.1'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
    // Aspect
    implementation libs.aspectj.tools
}

tasks.named('test') {
    useJUnitPlatform()
}
